### ISSUE TITLE
Quarto journal template

### ISSUE THREAD

**Issue by mvuorre** [crsh/papaja#540]
It looks like [Quarto](https://quarto.org/) is the new kid on the authoring tools block, and poised to replace (?) R Markdown in the future.

It would be awesome to have an APA PDF (& word I guess) Quarto template. 

I have also posted this issue on the Quarto journal templates repo: <https://github.com/quarto-journals/article-format-template/issues/11>, but I am not sure what is a better "home" for this, so am duplicating here.

See also: <https://quarto.org/docs/journals/formats.html>

**Comment by crsh** [comment]
Thanks for getting the discussion started, Matti. I do plan on adding a template here. As far as I can tell, to get this to work smoothly, we may need to translate some of our pre- and post-processing to Lua-filters, which is not my strongest skill. However, I would really like to support Quarto (as I like to use it and it may be an avenue to make the template available to Python, Julia, etc.). To decide where to best place this, I need to better understand how document templates in Quarto work. I know I won't get around to this before the end of the year. Anyway, if anyone is interested in helping out with this, any help is much appreciated.

**Comment by mscharkow** [comment]
I have succeeded somewhat in using the following YAML header to make a good-enough-for-me APA pdf:

```
---
title: "My article"
author: "Arnold Aardvark"
abstract: |
  This is a very short abstract.
format: 
  pdf:
    documentclass: apa7
    classoption: [man]
    include-in-header: 
      text: |
       \shorttitle{A shorter title}
       \affiliation{Institute of Stuff}

bibliography: references.bib
cite-method: biblatex
biblio-style: apa
---
```

This fails for more than one author because of the nonstandard way that apa7.csl handles this (\authorsnames{} etc.). I spend 10 minutes trying to fix this with some hack, but than my LaTeX PTSD kicked in. Maybe you know a quick fix.
